### ISSUE TITLE
Could not deserialize object to XML

### ISSUE THREAD

**Issue by alexgleason** [cternes/openkeepass#61]
Hi, I opened sorz/TinyKeePass#9 and then realized that TinyKeePass relies on this library, which is actually throwing the error.

I have a KeePass file that openkeepass cannot parse. It says "Could not deserialize object to XML." I wish I could provide the kdbx, but it contains real passwords.

The same kdbx can be opened properly with KeeWeb, KeePassDroid, and KeePass Tusk. It's possible the file is corrupted and these other tools are just very lenient when parsing the XML. I'm not sure how to check.

**Comment by alexgleason** [comment]
I opened the kdbx file with KeePass2 on Ubuntu and saved the file without making changes. This allowed the file to be parsed by openkeepass successfully.

This could be an issue with KeeWeb, which I used to create the file initially, although if the XML parser here were as lenient as the others that would be nice.

**Comment by timendum** [comment]
I've managed to replicate the error, see [attached file](https://github.com/cternes/openkeepass/files/1974752/New-2.zip).

The issue is due to [Property](https://github.com/cternes/openkeepass/blob/master/src/main/java/de/slackspace/openkeepass/domain/Property.java), KeeWeb saves a null Value (ie `<Value/>`) but the field is not nullable.

Can you make Property.propertyValue nullable?

Thanks.

**Comment by cternes** [comment]
Thank you for the investigation. I will have a look at it.

**Comment by timendum** [comment]
Anyway I've also opened [a ticket on keeweb](https://github.com/keeweb/kdbxweb/issues/21) and indeed KeePass opens file with null values.

**Comment by cternes** [comment]
I think I've found the issue. The problem was that keeweb rearranged the XML tags and that messed up my decryption. I've tested with the attached database file and it seems to work now.
